version: "3"

services:
  
  app:
    container_name: app
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db

  db:
    container_name: db
    image: postgres:13.10
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
  
  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A celery_worker.celery worker -B --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - app
      - redis
  
  # flower:
  #   container_name: flower
  #   build: .
  #   ports:
  #     - "5556:5555"
  #   command:
  #     - "celery"
  #     - "--broker=redis://redis:6379/0"
  #     - "flower"
  #     - "--broker_api=redis://redis:6379/0"
  #   depends_on:
  #     - app
  #     - redis
  #     - celery_worker

volumes:
  pgdata: