"""Second migration

Revision ID: 9caa4567a661
Revises: b292e651bc99
Create Date: 2024-11-11 21:54:28.340031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9caa4567a661'
down_revision = 'b292e651bc99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report', sa.String(length=1000), nullable=False),
    sa.Column('date', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_reports')
    # ### end Alembic commands ###
